#!/bin/sh
set -e

ln -sfn "$PWD/.bashrc" "$HOME/.bashrc"
ln -sfn "$PWD/.dircolors" "$HOME/.dircolors"
ln -sfn "$PWD/scripts" "$HOME/Scripts"

# Setup other configurations
for i in vim tmux sway alacritty; do
  cd $i && ./setup
  cd - >/dev/null
done
