#!/bin/sh
set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
ln -sf "$PWD/scripts" "$HOME/Scripts"

# Setup other configurations
for i in vim tmux; do
  cd $i && ./setup
  cd -
done
