#!/bin/bash

command -v vim >/dev/null 2>&1 || {
  echo >&2 "Vim not installed. (skip)"; exit 1;
}

ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
mkdir -p "$HOME/.vim/autoload"
ln -sfn "$PWD/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"
